name: sklearn_logreg_project

conda_env: conda.yaml

entry_points:
  main:
    parameters:
      data_path: {type: str, default: "data/synthetic.csv"}
      penalty: {type: str, default: "l2"}
      max_iter: {type: int, default: 100}
    command: "python train.py --data_path {data_path} --penalty {penalty} --max_iter {max_iter}"
